### ISSUE TITLE
Installation complains that tomopy-sacred.py does not exist

### ISSUE THREAD

**Issue by canismarko** [tomography/tomopy-cli#36]
I'm trying to install tomopy-cli according to the README. When I run ``python setup.py install``, I get an error message that ``bin/tomopy-sacred.py`` does not exist. If I change ``setup.py`` so that line 23 reads ``scripts=['bin/tomopy'],``, then it installs fine. I'm not sure if this is the correct solution since I don't know what is contained in tomopy-sacred.py.

**Comment by decarlof** [comment]
@canismarko I made the change in #37 . This was part of a test of [sacred](https://sacred.readthedocs.io) that I forgot to remove from my branch ...
