### ISSUE TITLE
Allow different output formats for reconstructed data

### ISSUE THREAD

**Issue by canismarko** [tomography/tomopy-cli#51]
Planning to submit a PR for this, but wanted to get input on how best to tie all the pieces together. This also potentially involves a change to dxchange.

Here's the **use case**: during this COVID-19 business, I've been running tomography reconstructions on APS workstations (eg. Mach and txmtwo). I then copy the tiffs over to my local machine in order to do the analysis/post-processing/visualization. I prefer to do this work directly on HDF5 datasets since it's easier on my computer's memory, especially for something like plotting a single XZ slice where reading the whole tiff stack into memory is not necessary. The first step after copying is to read all the tiffs and then save them into an HDF5 file. This is a waste of time and disk space since there's no reason I couldn't just save the reconstructed slices directly to the HDF5 file and copy that instead.

**My proposal:** Add a string-type configuration parameter *output-format* with the default value of ``"tiff"`` and choises of ``['tiff', 'hdf5']``. A value of ``"tiff"`` keeps the current behavior. If the value is ``"hdf5"``, then the reconstructed slices are saved in a new HDF5 file. If the input tomography data is *my_tomo_data.h5* then the output file would be *my_tomo_data_recon.h5* or something like that and have a dataset named *volume* with a *element_size_um* attribute holding the pixel size for compatibility with the ImageJ HDF5 plugin.

**dxchange:** I'd like to use dxchange for writing the HDF5 file, however I noticed that the *overwrite=True* option to dxchange's HDF writer seems to clobber the entire file, which could be dangerous if that file also has processed data in it or something like that. I would look into submitting a PR to dxchange to change that behavior to overwrite just the HDF5 dataset, not the whole HDF5 file.

Let me know what you think and if you would prefer I do it a different way.

**Comment by canismarko** [comment]
I wound up making a new *write_hdf* function in the *file_io.py* module of tomopy_cli that resembles the one in dxchange but is specifically meant for saving chunks of data as they get done being reconstructed.

**Comment by decarlof** [comment]
@canismarko I think adding the write_hdf in dxchange would be better and benefit a larger number of tomopy users (all use dxchange but not tomopy-cli yet)

**Comment by canismarko** [comment]
@decarlof I agree, but since tomopy-cli does the reconstructions in chunks, the interface wound up being specific to tomopy-cli and didn't really fit into dxchange. I'll see if I can re-write the function in dxchange in a more generic way, probably using chunks and allowing the HDF5 dataset to be resized if needed.
