### ISSUE TITLE
 rotation-axis tag

### ISSUE THREAD

**Issue by decarlof** [tomography/tomopy-cli#9]
rotation-axis is currently under file-reading. Makes it sense to move it under find-rotation-axis?

Also I would change [this](https://github.com/tomography/tomopy-cli/blob/053308c6895f80d8f59c0e696a0a6e4da2ee7451/tomopy_cli/find_center.py#L78) to use [write_hdf](https://github.com/tomography/tomopy-cli/blob/053308c6895f80d8f59c0e696a0a6e4da2ee7451/tomopy_cli/config.py#L491) so the rotation axis information is stored under /process/tomopy-cli-0.1/find-rotation-axis/rotation-axis.

Let me know if it is ok and I will make the changes

**Comment by decarlof** [comment]
@aps-7bm started to work on this issue:

This section of code: 
```
    with h5py.File(params.hdf_file,'r+') as hdf_file:
        hdf_file.require_dataset('/process/rot_center',shape=(1,), dtype=np.float64)
        hdf_file['/process/rot_center'][0] = rot_center
    log.info("  *** center written to /process/rot_center in file {0:f}".format(rot_center))
```
under [find_center.py](https://github.com/tomography/tomopy-cli/blob/053308c6895f80d8f59c0e696a0a6e4da2ee7451/tomopy_cli/find_center.py#L56) can be removed because the all config file information are saved when --hdf-file-save is set (see [write_hdf](https://github.com/tomography/tomopy-cli/blob/053308c6895f80d8f59c0e696a0a6e4da2ee7451/tomopy_cli/config.py#L487)).

**Comment by aps-7bm** [comment]
I'll need to change the code that tries to read this parameter as well.  Let me work on it a bit.

**Comment by decarlof** [comment]
@aps-7bm please have a look at my changes, I made already a change about location (under /processing/tomopy-cli2.0/rotation-axis)

**Comment by decarlof** [comment]
@aps-7bm I mean if you need to change that part perhaps is better to review/accept this pull request first so the automatic merge will still work
